#!/bin/bash

name: Build and push Docker image

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build and push Docker image
    runs-on: ubuntu-latest
    steps:
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v1
        with:
          version: latest
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: |
            ghcr.io/hugorcd/nestapi:latest
            ghcr.io/hugorcd/nestapi:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
